# Generated by Django 4.2.11 on 2024-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Cloths', 'Cloths'), ('Pants', 'Pants'), ('Shoes', 'Shoes'), ('Bag', 'Bags')], max_length=6),
        ),
    ]
